name: Build Client Application

on:
  push:
    paths:
      - 'src/**'

jobs:

  Build-Client-Application:
    name: Build Client Application
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.101
      - name: Build Net-Core WPF Application
        run: dotnet build --configuration Release src/client/PropertyManagement
